### PR TITLE
Oscilloscope

### PR DESCRIPTION
**Pull request by bessman**
This is a major overhaul of how analog channels are handled. Analog channel handling has been moved from the ScienceLab class to a new Oscilloscope class, located in a new oscilloscope module. The analogInputSource class has been renamed AnalogInput. The analogAcquisitionChannel data structure has been removed.

This PR also removes the broken calibration code, as discussed during last week's meeting.
~~This is a breaking change; the front end will require a corresponding PR which I will prepare.

~~While working on this I noticed some disparities between the code and the data sheet regarding sample rates. The data sheet says the achievable sample rates are:~~
- ~~1.1 Msps when sampling one or more channels at 10-bit resolution.~~
- ~~500 ksps when sampling a single channel at 12-bit resolution.~~

~~However, prior to this pull request the code suggests the following:~~
- ~~2 Msps when sampling a single channel _without trigger_ at 10-bit resolution (this is also the maximum sample rate stated on pslab.io)~~.
- ~~1 Msps when sampling a single channel _without trigger_ at 12-bit resolution.~~
- ~~667 ksps when sampling a single channel _with trigger_ at 10 or 12-bit resolution.~~
- ~~570 ksps when sampling >1 channel with or without trigger at 10-bit resolution.~~

~~Does anyone know more about where these sample rate figures come from? It should be straightforward to test the actual achievable sample rates under these conditions, which I plan to do and update the code accordingly.~~

Edit: From what I can tell, the minimum usable time base are the following (take the inverse to get the sample rate):

| Channels | No trigger    | Trigger    |
| :------------ | :---------------: | -----------: |
|  1             | 0.5 µs / 1µs* | 0.75 µs   |
|  2             | 0.875 µs       | 0.875 µs |
|  4             | 1.75 µs         | 1.75 µs   |

*12-bit

Which is better than the data sheet, except when sampling four channels where we only get half of what the data sheet claims.

TODOs:
- [x] Corresponding pull request to front end.
- [x] Experiment with sample rate.
- [x] Unit tests

Known regressions (wontfix for now, will be addressed in a later PR):
- Capacitance measurement may fail (not sure under which specific conditions).

Also, Codacy is probably going to complain a lot about this PR because sciencelab.py is now small enough that it will be included in the analysis.

### CODE REVIEW

**Comment by fcartegnie** [comment]
> Edit: From what I can tell, the minimum usable time base are the following (take the inverse to get the sample rate):
> Channels 	No trigger 	Trigger
> 1 	0.5 µs / 1µs* 	0.75 µs
> 2 	0.875 µs 	0.875 µs
> 4 	1.75 µs 	1.75 µs

page 323~

- 12 bit -> 500 ksps
- 10 bit -> 1100 ksps
Conversion speed != sampling clock rate != sampling rate.
Conversion is driving sampled data output.

Page 471 example:
Conversion is reading the bits from the Op Amp Outputs.
14 tCONV + 3 tSAMP = 17 tAD = 17 * 117.6 ns ~~ 500ksps

**Comment by fcartegnie** [comment]
More details with the ADC part spec:
http://ww1.microchip.com/downloads/en/DeviceDoc/70621c.pdf

**Comment by fcartegnie** [comment]
4 channels only exists in 10bit mode according to 

bit 10 AD12B: ADC 10-Bit or 12-Bit Operation Mode bit (1)
1 = 12-bit, 1-channel ADC operation
0 = 10-bit, 4-channel ADC operation

**Comment by bessman** [comment]
It seems the real-world performance of the ADC exceeds the specifications then, at least for single-channel operation. This is simple to verify. Connect SI1 to CH1 and run the following piece of code:
```python
import matplotlib.pyplot as plt
from PSL import sciencelab

I = sciencelab.connect()
I.set_sine1(freq=200)
x, y = I.oscilloscope.capture(channels=1, samples=10000, timegap=0.5)
plt.plot(x, y)
plt.show()
```
Result:

10 000 samples captured within one period of a 200 Hz signal, i.e. 5 ms. 10 ks / 5e-3 s = 2 Ms / s.

**Comment by fcartegnie** [comment]
> 10 000 samples captured within one period of a 200 Hz signal, i.e. 5 ms. 10 ks / 5e-3 s = 2 Ms / s. I arrived at the other values in the table in a similar manner.

Seems that's doing auto sampling with manual conversion.
Need to figure which firmware procedure is called and fully interpret the register parameters to really understand what is done.

**Pull request merged**
