### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by 19-pragya**
Issue : #127

### CODE REVIEW

**Comment by bessman** [comment]
Hi pragya, thank you for the pull request! Could you add add a description explaining your changes, please?

**Comment by 19-pragya** [comment]
Actually , i was trying to divide it into modules.. (sciencelab ) it was asked to divide the components of this large script into smaller modules so...i did only for installation

**Comment by bessman** [comment]
I see! May I ask how much experience you have with Python? As you can see from the Travis CI build, your changes currently do not work. Moving methods out of a class and turning them into standalone functions require careful consideration to avoid breaking something, since methods often depend on instance variables which cannot be used by standalone functions. In this case, the methods you've chosen exist only to initialize new ScienceLab instances, so turning them into functions will not work.

What might work is to create a ScienceLabFactory class, moving the initialization there, and making the ScienceLab class inherit from it. If you want to try doing that, please put the new class in the PSL package, not the tests package. The latter is for unit tests.

**Review by mohsinmahmood12 — APPROVED** [review]

**Comment by bessman** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
