### PR TITLE
Optimised Images

### PR DESCRIPTION
**Pull request by agarwalutkarsh554**

### CODE REVIEW

**Comment by agarwalutkarsh554** [comment]
Please check my pull request

**Comment by bessman** [comment]
Hi, thanks for making the images smaller. However, the images are all out of date and will be removed as part of the 2.0 release, so there is actually no need to optimize them.

**Comment by agarwalutkarsh554** [comment]
Can you tell me any other new repositories to which i can contribute to

**Comment by bessman** [comment]
Well, what free software do you frequency use yourself? Check if any of those could use any help.

**Pull request closed without merging**
