### PR TITLE
update tria function

### LINKED ISSUE #218: Update triangle waveform function to match pslab-android
https://github.com/fossasia/pslab-android/pull/2364

### PR DESCRIPTION
**Pull request by suvanbanerjee**
Changed the function to `abs(x % 4 - 2)` and span to `[0, 4]`
@bessman  I don't have the required hardware to record the serial traffic.
Closes #218

### CODE REVIEW

**Comment by suvanbanerjee** [comment]
@bessman please confirm is this correct or I have to do something else.

**Comment by bessman** [comment]
There is some kind of problem with the new implementation. Blue curve is old, orange is new:
update_tria

I can't immediately see what the problem is. I'll give it a think and get back to you.

**Comment by bessman** [comment]
Only the span should be changed, not the function. The -1 in the function is necessary to get correct analog offset; pslab-android corrects for this offset in loadTable instead.

Please revert the change to `tria`, but keep the new span. Replace the recorded test data (tests/recordings/waveform_generator/test_triangle_wave.json) with this updated recording: [test_triangle_wave.json](https://github.com/fossasia/pslab-python/files/15346730/test_triangle_wave.json)

Verify that the test passes (`pytest -k test_triangle_wave`), then update the PR.

**Comment by suvanbanerjee** [comment]
@bessman test are working fine
image

**Review by bessman — APPROVED** [review]

**Pull request merged**
