### PR TITLE
Refactor logic analyzer

### PR DESCRIPTION
**Pull request by bessman**
Move logic analyzer related functionality to a separate module. API has been updated to resemble the new oscilloscope module. Still more work to be done, including:

- [x] Documentation
- [x] Tests
- [x] Corresponding changes to pslab-desktop

### CODE REVIEW

**Comment by orangecms** [comment]
From Gitter:

> When run as integration tests, the SQ1-4 pins should be connected to the LA1-4 pins, and in order for the tests to pass both the logic analyzer and waveform generator must work as expected on software, firmware, and hardware level.

> To run the integration tests, checkout #132, install `pytest`, and run `pytest --integration tests` from the project root.

I ran the tests three times, and one case failed for every run:

```
pytest --integration tests                                             13.3s  Sat 05 Sep 2020 01:31:31 PM UTC
================================================================= test session starts =================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/dan/Projects/fossasia/pslab-python
collected 85 items

tests/test_achan.py .........                                                                                                                   [ 10%]
tests/test_analytics.py ......                                                                                                                  [ 17%]
tests/test_logic_analyzer.py ...............F.............                                                                                      [ 51%]
tests/test_oscilloscope.py ................                                                                                                     [ 70%]
tests/test_packet_handler.py .........................                                                                                          [100%]

====================================================================== FAILURES =======================================================================
________________________________________________________________ test_measure_interval ________________________________________________________________

scaffold = <PSL.logic_analyzer.LogicAnalyzer object at 0x7f0e7c8a2100>

    def test_measure_interval(scaffold):
        scaffold.configure_trigger("ID1", "falling")
        interval = scaffold.measure_interval(
            channels=["ID1", "ID2"], modes=["rising", "falling"], timeout=0.1
        )
        expected_interval = FREQUENCY ** -1 * -PHASE * MICROSECONDS
>       assert expected_interval == pytest.approx(interval, rel=RELTOL)
E       assert -2.5 == -2.5625 ± 5.1e-02
E        +  where -2.5625 ± 5.1e-02 = <function approx at 0x7f0e7e7300d0>(-2.5625, rel=0.02)
E        +    where <function approx at 0x7f0e7e7300d0> = pytest.approx

tests/test_logic_analyzer.py:232: AssertionError
---------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------
Radio transceiver not installed/not found
=============================================================== short test summary info ===============================================================
FAILED tests/test_logic_analyzer.py::test_measure_interval - assert -2.5 == -2.5625 ± 5.1e-02
============================================================ 1 failed, 84 passed in 14.01s ============================================================
```

Otherwise, it all passes. Is that related to tolerance?

**Comment by bessman** [comment]
Yes, that test checks the measure_interval method, which measures the time in microseconds between two logic events. In this case, it measures the time between a rising edge on LA1 and a falling edge on LA2. The frequency of both signals is 100 kHz and the phase of the signal on LA2 is shifted by 25% relative to the signal on LA1. Both have a duty cycle of 50%.

The measurement starts when a falling edge is detected on LA1. A rising edge occurs half a period later, i.e. 5 µs. However, since the signal on LA2 is 25% ahead of LA1, a falling edge occurs already 2.5 µs after measurement start, i.e. 2.5 µs before the event on LA1. The expected result is therefore -2.5.



You're getting -2.6425, which is about 2.5% too high. The relative tolerance is set to 2%, so the test fails. At the top of the file is a variable called RELTOL. If you increase it to 0.025 the test should pass.

Let's discuss during the meeting what kind of tolerances we can accept.

**Comment by orangecms** [comment]
Connecting all LA pins to SQ1:

```
 pytest --integration tests                                                 267ms  Sat 05 Sep 2020 08:39:19 PM UTC
================================================================= test session starts =================================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/dan/Projects/fossasia/pslab-python
collected 85 items

tests/test_achan.py .........                                                                                                                   [ 10%]
tests/test_analytics.py ......                                                                                                                  [ 17%]
tests/test_logic_analyzer.py ...............F...........F.                                                                                      [ 51%]
tests/test_oscilloscope.py ................                                                                                                     [ 70%]
tests/test_packet_handler.py .........................                                                                                          [100%]

====================================================================== FAILURES =======================================================================
________________________________________________________________ test_measure_interval ________________________________________________________________

scaffold = <PSL.logic_analyzer.LogicAnalyzer object at 0x7f1d014c5eb0>

    def test_measure_interval(scaffold):
        scaffold.configure_trigger("ID1", "falling")
        interval = scaffold.measure_interval(
            channels=["ID1", "ID2"], modes=["rising", "falling"], timeout=0.1
        )
        expected_interval = FREQUENCY ** -1 * -PHASE * MICROSECONDS
>       assert expected_interval == pytest.approx(interval, rel=RELTOL)
E       assert -2.5 == 4.953125 ± 9.9e-02
E        +  where 4.953125 ± 9.9e-02 = <function approx at 0x7f1d033b50d0>(4.953125, rel=0.02)
E        +    where <function approx at 0x7f1d033b50d0> = pytest.approx

tests/test_logic_analyzer.py:232: AssertionError
---------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------
Radio transceiver not installed/not found
___________________________________________________________________ test_get_states ___________________________________________________________________

scaffold = <PSL.logic_analyzer.LogicAnalyzer object at 0x7f1d014f69a0>

    def test_get_states(scaffold):
        time.sleep(LOW_FREQUENCY ** -1)
        states = scaffold.get_states()
        expected_states = {"ID1": True, "ID2": False, "ID3": False, "ID4": True}
>       assert states == expected_states
E       AssertionError: assert {'ID1': True,..., 'ID4': True} == {'ID1': True,..., 'ID4': True}
E         Omitting 2 identical items, use -vv to show
E         Differing items:
E         {'ID2': True} != {'ID2': False}
E         {'ID3': True} != {'ID3': False}
E         Use -v to get the full diff

tests/test_logic_analyzer.py:331: AssertionError
---------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------
Radio transceiver not installed/not found
=============================================================== short test summary info ===============================================================
FAILED tests/test_logic_analyzer.py::test_measure_interval - assert -2.5 == 4.953125 ± 9.9e-02
FAILED tests/test_logic_analyzer.py::test_get_states - AssertionError: assert {'ID1': True,..., 'ID4': True} == {'ID1': True,..., 'ID4': True}
============================================================ 2 failed, 83 passed in 12.35s ============================================================
```

**Comment by orangecms** [comment]
When running

```python
from PSL import sciencelab

psl = sciencelab.connect()
psl.sqrPWM(1e5, 0.5, 0, 0.5, 0, 0.5, 0, 0.5)
t1, t2, t3, t4 = psl.logic_analyzer.capture(4)
for t in (t2, t3, t4):
    print(t1 - t)
```

I get:

```
Radio transceiver not installed/not found
[0.03125 0.03125 0.03125 ... 0.03125 0.03125 0.03125]
[0.0625 0.0625 0.0625 ... 0.0625 0.0625 0.0625]
[0.09375 0.09375 0.09375 ... 0.09375 0.09375 0.09375]
```

**Comment by bessman** [comment]
Interesting. That's what I get too. What do you get run:
```python
from PSL import sciencelab

psl = sciencelab.connect()
psl.sqrPWM(1e5, 0.5, 0, 0.5, 0, 0.5, 0, 0.5)
t1, t2, t3, t4 = psl.logic_analyzer.capture(4 ,modes=["rising","faling","rising","falling"])
for t in (t2, t3, t4):
    print(t1 - t)
```

**Comment by bessman** [comment]
There seems to be a two clock cycle offset between channels in multi-channel mode. After compensating for that, I was able to replace the 2% relative tolerance (which was just an arbitrary value that happened to work (mostly)) with a single clock cycle absolute tolerance. That's as good as we're going to get; whether we get exactly the expected value or one clock cycle off is a matter of chance.

Let me know if the tests pass on your device.

**Comment by orangecms** [comment]
Awesome, it is now passing completely, both for all LA pins on SQ1 and for LA1 -> SQ1 etc separately. :)

**Review by orangecms — APPROVED** [review]

**Pull request merged**
